sonar.projectKey=posthog-terraform-provider
sonar.projectName=PostHog Terraform Provider
sonar.sourceEncoding=UTF-8

sonar.sources=main.go,internal
sonar.tests=internal,testacc
sonar.test.inclusions=internal/**/*_test.go,testacc/**/*_test.go
sonar.exclusions=vendor/**,tools/**,bin/**,playground/**,examples/**,docs/**

sonar.go.coverage.reportPaths=coverage.out
