#!/usr/bin/env bash

set -euo pipefail

ENV_FILE=".op-bootstrap.env"
RUNTIME_ENV_FILE=".env"

usage() {
  cat <<'EOF'
Usage: ./scripts/sync-1password-item.sh [--env-file PATH] [--runtime-env PATH]

Reads raw PostHog values from a local bootstrap env file, creates or updates the
target 1Password item, then writes a provider runtime `.env` file with `op://`
references that match the created fields.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file)
      ENV_FILE="$2"
      shift 2
      ;;
    --runtime-env)
      RUNTIME_ENV_FILE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if ! command -v op >/dev/null 2>&1; then
  echo "1Password CLI 'op' is required but was not found in PATH." >&2
  exit 1
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Bootstrap env file not found: $ENV_FILE" >&2
  exit 1
fi

if ! op whoami >/dev/null 2>&1; then
  echo "1Password CLI is not signed in. Run 'op whoami' or 'op signin' first." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

require_var() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "Required variable '$name' is empty in $ENV_FILE" >&2
    exit 1
  fi
}

require_var "ONEPASSWORD_VAULT"
require_var "ONEPASSWORD_ITEM"
require_var "POSTHOG_API_KEY"
require_var "POSTHOG_PROJECT_ID"
require_var "POSTHOG_HOST"
require_var "POSTHOG_ORGANIZATION_ID"

TMP_JSON="$(mktemp)"
cleanup() {
  rm -f "$TMP_JSON"
}
trap cleanup EXIT

ITEM_EXISTS=0
if op item get "$ONEPASSWORD_ITEM" --vault "$ONEPASSWORD_VAULT" --format json >"$TMP_JSON" 2>/dev/null; then
  ITEM_EXISTS=1
else
  op item template get "Secure Note" >"$TMP_JSON"
fi

export TMP_JSON
python3 <<'PY'
import json
import os

path = os.environ["TMP_JSON"]

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

data["title"] = os.environ["ONEPASSWORD_ITEM"]
data["category"] = "SECURE_NOTE"

fields = data.get("fields", [])

note_value = (
    "Managed for posthog-terraform-lab/provider.\n"
    "Field labels in this item are consumed by provider/.env op:// references."
)

notes_field = None
for field in fields:
    if field.get("id") == "notesPlain" or field.get("purpose") == "NOTES":
        notes_field = field
        break

if notes_field is None:
    fields.append(
        {
            "id": "notesPlain",
            "type": "STRING",
            "purpose": "NOTES",
            "label": "notesPlain",
            "value": note_value,
        }
    )
else:
    notes_field["value"] = note_value

desired_fields = [
    ("api_key", "CONCEALED", os.environ["POSTHOG_API_KEY"]),
    ("project_id", "STRING", os.environ["POSTHOG_PROJECT_ID"]),
    ("host", "STRING", os.environ["POSTHOG_HOST"]),
    ("organization_id", "STRING", os.environ["POSTHOG_ORGANIZATION_ID"]),
    ("test_user_email", "STRING", os.environ.get("POSTHOG_TEST_USER_EMAIL", "")),
]

for label, field_type, value in desired_fields:
    existing = None
    for field in fields:
      if field.get("id") == label or field.get("label") == label:
        existing = field
        break

    if existing is None:
        fields.append(
            {
                "id": label,
                "label": label,
                "type": field_type,
                "value": value,
            }
        )
    else:
        existing["id"] = label
        existing["label"] = label
        existing["type"] = field_type
        existing["value"] = value

data["fields"] = fields

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f)
PY

if [[ "$ITEM_EXISTS" -eq 1 ]]; then
  op item edit "$ONEPASSWORD_ITEM" --vault "$ONEPASSWORD_VAULT" --template "$TMP_JSON" >/dev/null
  ACTION="updated"
else
  op item create --vault "$ONEPASSWORD_VAULT" --template "$TMP_JSON" >/dev/null
  ACTION="created"
fi

cat >"$RUNTIME_ENV_FILE" <<EOF
# Generated by ./scripts/sync-1password-item.sh
# Secrets are stored in 1Password and resolved at runtime with: op run --env-file=.env -- <command>

POSTHOG_API_KEY=op://$ONEPASSWORD_VAULT/$ONEPASSWORD_ITEM/api_key
POSTHOG_PROJECT_ID=op://$ONEPASSWORD_VAULT/$ONEPASSWORD_ITEM/project_id
POSTHOG_HOST=op://$ONEPASSWORD_VAULT/$ONEPASSWORD_ITEM/host
POSTHOG_ORGANIZATION_ID=op://$ONEPASSWORD_VAULT/$ONEPASSWORD_ITEM/organization_id
POSTHOG_TEST_USER_EMAIL=op://$ONEPASSWORD_VAULT/$ONEPASSWORD_ITEM/test_user_email
EOF

echo "1Password item '$ONEPASSWORD_ITEM' in vault '$ONEPASSWORD_VAULT' $ACTION."
echo "Runtime env file written to $RUNTIME_ENV_FILE."
